name: Update Exchange Rate

on:
  schedule:
    - cron: '30 1 * * *' # 每天UTC时间01:30，相当于北京时间09:30
  workflow_dispatch: # 手动触发

jobs:
  update-exchange-rate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch exchange rate from Alpha Vantage
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          EXCHANGE_RATE=$(curl -s "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=USD&to_currency=CNY&apikey=$ALPHA_VANTAGE_API_KEY" | jq -r '.["Realtime Currency Exchange Rate"]["5. Exchange Rate"]')
          echo "Exchange rate: $EXCHANGE_RATE"
          echo "::set-output name=exchange_rate::$EXCHANGE_RATE"

      - name: Update exchange rate file
        run: |
          echo "{ \"exchangeRate\": \"$EXCHANGE_RATE\" }" > exchange_rate.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add exchange_rate.json
          git commit -m "Update exchange rate"
          git push
